AWSTemplateFormatVersion: "2010-09-09"
Resources:
    LambdaFunction:
        Properties:
            Code:
                S3Bucket: gadget-init-deploybucket-kfh2vfsg8pgs
                S3Key: lambda.zip
            Environment:
                Variables:
                    s3myBucket:
                        Ref: s3myBucket
            Handler: remote
            Role:
                Fn::GetAtt:
                    - LambdaRole
                    - Arn
            Runtime: go1.x
        Type: AWS::Lambda::Function
    LambdaRole:
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Action: sts:AssumeRole
                      Effect: Allow
                      Principal:
                        Service: lambda.amazonaws.com
                Version: "2012-10-17"
            Policies:
                - PolicyDocument:
                    Statement:
                        - Action: '*'
                          Effect: Allow
                          Resource: '*'
                    Version: "2012-10-17"
                  PolicyName: AllPrivileges
        Type: AWS::IAM::Role
    s3myBucket:
        Properties:
            BucketName: stefansiprell1979test
        Type: AWS::S3::Bucket
